language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install .
script:
- install-chromedriver
notifications:
  email:
    on_success: never
    on_failure: always
    on_start: never
    on_cancel: never
    on_error: always
